### PR TITLE
Set up react and redux

### PR DESCRIPTION
**Pull request by jcmunav63**
### Description
By now you've used many different gems with Rails and this exercise will have you connect previous knowledge with new knowledge as you get a chance to use Webpack with jsbundling-rails gem.

### General requirements
- Make sure that there are [no linter errors](https://github.com/microverseinc/linters-config).
- Make sure that you used the correct [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md).
- Make sure that you documented your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).

### Ruby requirements
- Follow our list of [best practices for Ruby](https://github.com/microverseinc/curriculum-ruby/blob/main/articles/ruby_best_practices.md).
NOTE: Use Rails >=7 for this project so that you can follow the guidelines and instructions included in the curriculum. If you need help installing different versions of Rails, check this [tutorial](https://github.com/sinansevgi/reviewer-experiments/blob/main/specific_rails.md).

### Project requirements
- Create a new Rails app called 'hello-rails-react'.
   - Use the command rails new -j webpack my_new_rails_app as described in the previous lesson's tutorial.
- Verify that the jsbundling-rails gem is added to your Gemfile.
- Initialize your project with Git.
- Install needed node dependencies as described in the previous lesson's tutorial.
- Create a babel.config.js in the root folder of your project as described in the previous lesson's tutorial.
- Update webpack.config.js to include the babel loader as described in the previous lesson's tutorial.
- Make sure that your project has a Postgres database set up.
- Create a table for storing your messages and create 5 different greetings.
- Create an API endpoint that selects a random greeting from your table (you will need a controller with an action and Rails route).
- Create a static view that will be the root of your app.
--------------
- Create the App component with react-router and render it in your static view.
- Create the Greeting component that will display a greeting. Set it up as a route in your App component.
- Create a store, an action, and a reducer that will connect to your API endpoint to get the random greeting.
- Display the random greeting in your Greeting component.

Evidence:

Message on the **API endpoint** (Rails):
image

Message on the browser (**React component**):
image

### CODE REVIEW

**Review by skyv26 — CHANGES_REQUESTED** [review]
## Hi @jcmunav63, 

Good job so far 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

## STATUS: REQUIRE CHANGES 🔴 




## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implement the features ✅ 

## Required Changes ♻️
- [ ] Well done @jcmunav63, you did a great job so far, as I can see that you implemented the functionalities for both front-end and back-end. But I can't approve your project because you are not fulfilling the requirements properly. I agree with the screenshots you attached in the PR description, which seems like you ran a back-end application on a different port like `3000` and a front-end application on the `3001` port. But in actuality, you should run both `front-end` and `back-end` services on the same port. This means you should not run `separate` servers on the system. Just `./bin/dev` your server should run automatically and the front-end builds the file automatically based on the changes you will make on the components etc.

- [ ] Based on what I mentioned above let me clarify a few things using screenshots, as you can see below in the screenshot you are rendering the `App` component which is just returning the `Message` string but not the whole `frontend` folder, which does contain all the functionality of the application that you were running on the separate server.

code

- [ ] Please follow the `article` provided in the project requirements for `creating` one application `Rails project` using `js_bundling` power properly. Because the solution you provided is a `two app`  project within the same folder.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

#### Cheers, and Happy coding!👏👏👏

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   @skyv26
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   linkedin-skyv2022
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   @vrma_aakash
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   @skybrel
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   @skybrel
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jcmunav63** [comment]
I have tried to follow the lessons and other articles or posts, but they
aré incomplete, and the app doesn't render anyrhing, using webpack, and
jsbundling. I don't know how you ask something that is more difficult to
achieve, when there aré simpler ways to do it.
I supone I won't finish the program. Thanks a lot

**Comment by skyv26** [comment]
@jcmunav63 Please let me know whenever you will be free and I will show you the instructions on the article will work without any problem by following instructions step by step. Even I will help you to run your project on the same port.

**Comment by jcmunav63** [comment]
Hello, Aakash. Good day.

I didn't know that you need to run in the same port these two servers. The
article doesn't tell you this. And the command ./bin(dev is only useful on
Linux or Mac, not on Windows.

So I'm trying to use the YARN command: yarn buid --watch , and it worked
for a simple page with an <h1> tag.

But, when I include all the code, with components, actions, reducers and
store, it displays the following errors, about software that I have
previously installed.

Here are the messages and ERRORS...
C:\Users\rcbuc\MICROVERSE\MODULE6_FINAL_CAPSTONE\rails-react-hello-one>
yarn build --watch
yarn run v1.22.4
$ webpack --config webpack.config.js --watch
assets by status 237 KiB [cached] 1 asset
orphan modules 210 KiB [orphan] 20 modules
runtime modules 670 bytes 3 modules
cacheable modules 353 KiB
  modules by path ./node_modules/react-dom/ 131 KiB
    ./node_modules/react-dom/client.js 619 bytes [built] [code generated]
 ./node_modules/react-dom/index.js 1.33 KiB [built] [code generated]
    ./node_modules/react-dom/cjs/react-dom.production.min.js 129 KiB
[built] [code generated]
  modules by path ./node_modules/react/ 6.94 KiB
    ./node_modules/react/index.js 190 bytes [built] [code generated]
    ./node_modules/react/cjs/react.production.min.js 6.75 KiB [built] [code
generated]
  modules by path ./node_modules/scheduler/ 4.33 KiB
    ./node_modules/scheduler/index.js 198 bytes [built] [code generated]
    ./node_modules/scheduler/cjs/scheduler.production.min.js 4.14 KiB
[built] [code generated]
  ./app/javascript/application.js + 11 modules 192 KiB [built] [code
generated]
  .***@***.***/actioncable/src/index.js + 9 modules 19.8 KiB
[built] [code generated]

ERROR in ./app/javascript/actions/greetingActions.js 1:0-26
Module not found: Error: Can't resolve 'axios' in
'C:\Users\rcbuc\MICROVERSE\MODULE6_FINAL_CAPSTONE\rails-react-hello-one\app\javascript\actions'

 @ ./app/javascript/reducers/greetingReducer.js 1:0-116 9:9-31 15:9-31
21:9-31
 @ ./app/javascript/store.js 2:0-57 5:14-29
 @ ./app/javascript/application.js 18:0-28 22:9-14

ERROR in ./app/javascript/application.js 17:0-39
Module not found: Error: Can't resolve 'react-redux' in
'C:\Users\rcbuc\MICROVERSE\MODULE6_FINAL_CAPSTONE\rails-react-hello-one\app\javascript'


ERROR in ./app/javascript/components/App.js 2:0-74
Module not found: Error: Can't resolve 'react-router-dom' in
'C:\Users\rcbuc\MICROVERSE\MODULE6_FINAL_CAPSTONE\rails-react-hello-one\app\javascript\components'
 @ ./app/javascript/application.js 20:0-35 23:36-39

ERROR in ./app/javascript/components/Greeting.js 2:0-55
Module not found: Error: Can't resolve 'react-redux' in
'C:\Users\rcbuc\MICROVERSE\MODULE6_FINAL_CAPSTONE\rails-react-hello-one\app\javascript\components'
 @ ./app/javascript/components/App.js 3:0-34 7:44-52
 @ ./app/javascript/application.js 20:0-35 23:36-39

ERROR in ./app/javascript/store.js 1:0-50
Module not found: Error: Can't resolve ***@***.***/toolkit' in
'C:\Users\rcbuc\MICROVERSE\MODULE6_FINAL_CAPSTONE\rails-react-hello-one\app\javascript'
 @ ./app/javascript/application.js 18:0-28 22:9-14

5 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.91.0 compiled with 5 errors in 6019 ms

Can you help me to run this project, please?

Juan Carlos Muñoz Navarrete
Module 6 student

**Comment by jcmunav63** [comment]
With the help of my code reviewer, Aakash Verma, I could config the .bin/dev command option, to run this project using one console and one port (3000), running Webpack server in watch mode, and running Rails server on port 3000.

Here are two images of the console...

Console showing the **Webpack server** compiling the React app...
image

Console running the **Rails server**...
image

Displayed **Random Message** (in Chrome browser)...
image

Thank you.

**Review by skyv26 — APPROVED** [review]
## Hi @jcmunav63, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## STATUS: APPROVED 🟢 



## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implement the features ✅ 
image


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   @skyv26
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   linkedin-skyv2022
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   @vrma_aakash
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   @skybrel
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   @skybrel
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jcmunav63** [comment]
Thank you very much, Aakash! Have a great week!

**Pull request merged**
